name: OWASP Scan

description: |
  An action to run an OWASP scan on a report

inputs:
  download-artifacts:
    description: Whether artifacts (Maven state, compiled classes and JARs) should be downloaded
    default: 'true'
    required: false
  nvd-api-key:
    description: The API key for the NVD database, used by the dependency-check scan plugin
    required: true

runs:
  using: composite

  steps:
    - name: Set up ${{ inputs.graalvm-distribution }} ${{ inputs.graalvm-version }} (Java ${{ inputs.java-version }})
      uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'

    - name: OWASP DB Cache
      uses: actions/cache@v4
      with:
        path: owasp-db
        key: owasp-db

    - name: Download Maven State
      uses: actions/download-artifact@v4
      if: ${{ inputs.download-artifacts == 'true' }}
      with:
        name: maven-state

    - name: Download Compiled Classes
      uses: actions/download-artifact@v4
      if: ${{ inputs.download-artifacts == 'true' }}
      with:
        name: compiled-classes

    - name: Download JARs
      uses: actions/download-artifact@v4
      if: ${{ inputs.download-artifacts == 'true' }}
      with:
        name: jars

    - name: OWASP CVE Scan
      shell: sh
      run: |
        ./mvnw \
          --batch-mode \
          --color always \
          --define ci-owasp \
          --define dataDirectory=owasp-db \
          --define nvdApiKey=${{ inputs.nvd-api-key }} \
          package

    - name: Upload OWASP Scan Report
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        if-no-files-found: error
        name: owasp-report
        path: '**/target/owasp/*.xml'
        retention-days: 2

    - name: Publish Report
      if: ${{ always() }}
      uses: turing85/publish-report@v2
      with:
        report-list-tests: failed
        report-name: OWASP Scan
        report-path: '**/target/owasp/*.xml'