name: Populate Cache

description: |
  An action to populate the maven cache, if no cache exists.
inputs:
  nvd-api-key:
    description: The API key for the NVD database, used by the dependency-check scan plugin
    required: true

runs:
  using: composite

  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'
      id: setup

    - name: Populate Cache
      if: ${{ steps.setup.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        ./mvnw \
          --batch-mode \
          --color always \
          --define ci-populate-cache \
          --define nvdApiKey=${{ inputs.nvd-api-key }} \
          dependency:go-offline verify