name: Populate Cache

description: |
  An action to populate the maven cache, if no cache exists.

runs:
  using: composite

  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'
      id: setup

    - name: Populate Cache
      if: ${{ steps.setup.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        ./mvnw \
          --batch-mode \
          --color always \
          --define ci-populate-cache \
          dependency:go-offline verify