name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE.txt'
      - '**.md'
      - '**.adoc'
      - '**.txt'
      - '.all-contributorsrc'
      - 'localdeployment/docker-compose.yml'
  pull_request:
    paths-ignore:
      - '**.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE.txt'
      - '**.md'
      - '**.adoc'
      - '**.txt'
      - '.all-contributorsrc'
      - 'localdeployment/docker-compose.yml'

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'turing85/spring-file-upload' }}

permissions:
  actions: write
  checks: write
  pull-requests: write

jobs:
  recreate-comment:
    name: Recreate Comment
    runs-on: ubuntu-latest

    steps:
      - name: Publish Report
        uses: turing85/publish-report@v2
        with:
          checkout: 'true'
          recreate-comment: true

  populate-cache:
    name: Populate Cache
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - name: Populate cache
        uses: ./.github/actions/populate-cache

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    needs:
      - recreate-comment
      - populate-cache

    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test
        run: |
          ./mvnw \
            --batch-mode \
            --color always \
            --define ci \
            clean package

      - name: Upload Maven State
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          if-no-files-found: error
          name: maven-state
          path: '**/target/maven-*'
          retention-days: 2

      - name: Upload Compiled Classes
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          if-no-files-found: error
          name: compiled-classes
          path: '**/target/*classes'
          retention-days: 2

      - name: Upload JARs
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          if-no-files-found: error
          name: jars
          path: '**/target/*.jar'
          retention-days: 2

      - name: Upload Unit Test Report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: unit-test-report
          path: '**/target/cucumber-reports/*.xml'
          if-no-files-found: error
          retention-days: 2

      - name: Publish Report
        if: ${{ always() }}
        uses: turing85/publish-report@v2
        with:
          report-name: Unit Test
          report-path: '**/target/cucumber-reports/*.xml'

  owasp:
    name: OWASP Scan
    runs-on: ubuntu-latest

    needs:
      - build-and-test

    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - name: OWASP Scan
        uses: ./.github/actions/owasp
        with:
          nvd-api-key: ${{ secrets.NVD_API_KEY }}

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    needs:
      - build-and-test

    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - name: Integration Test
        uses: ./.github/actions/integration-test