name: Nightly CVE Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  checks: write

jobs:
  populate-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Populate cache
        uses: ./.github/actions/populate-cache
        with:
          nvd-api-key: ${{ secrets.NVD_API_KEY }}

  owasp:
    runs-on: ubuntu-latest

    needs:
      - populate-cache

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/owasp
        with:
          download-artifacts: false
          nvd-api-key: ${{ secrets.NVD_API_KEY }}